
language: node_js
node_js:"9"
install:
  - npm install
script: npm run dist-win
deploy:
  provider: releases
  file_glob: true
  file: "dist/*.*"
  skip_cleanup: true

  on:
    repo: lixm1988/electron_quich_start
    # all_branches: true
    tags: true
