os: windows
language: node_js
# nodejs版本
  node_js: "10"

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run dist-win
# E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
deploy:
  provider: releases	
  file_glob: true	# 无其他依赖项所以执行npm run build 构建就行了
  file: "dist/*.*"
  skip_cleanup: true
env:
 global:
   # 我将其添加到了travis-ci的环境变量中
   #- GH_REF: github.com/yimogit/metools.git 
